###############################
# DO NOT TOUCH CONFIG_VERSION #
###############################
# CONFIG_VERSION GETS UPDATED #
# ALONGSIDE DEVELOPMENT AND   #
# IT ALLOWS THE PLUGIN TO     #
# MIGRATE OLD CONFIGS TO NEW  #
# CONFIGS AUTOMATICALLY       #
###############################
# IF THE PLUGIN DETECTS       #
# A MISMATCHED CONFIG VERSION #
# OR ONE THAT IS NOT OFFICIAL #
# IT WILL NOT START           #
###############################
CONFIG_VERSION: 1

###############################
#     General Configuration   #
###############################
isSafeUserMap: true

###############################
# Database Connection (MYSQL) #
###############################
database:
  ip: "localhost"
  port: 3306
  username: ""
  password: ""

###############################
# Schematics Section          #
# Supported APIs: FAWE & W/E  #
###############################

schematics:
  location: "/schematics/"
  loader: "FAWE"

###############################
#       Betting Section       #
# Cash Bets Min and Max Cap   #
# Are in %, Its the return    #
# The better get if their     #
# bet wins.                   #
###############################
betting:
  cash:
    min_sum: 100.0
    max_sum: 100000.0
    min_return_cap: 1.0
    max_return_cap: 13.0
  opposing:
    select_kit_cap: 5000.0
    select_challenge: 10000.0

###############################
#         Duels (Global)      #
###############################


# Duel ID Type changes the format of the duel ID
# Available types are 4DIG, 6DIG and HEX
# 4DIG Example: 0123
# 6DIG Example: 012345
# HEX  Example: AB12
duel_id_type: "4DIG"

# The delay, in seconds, required between /home, /tp, etc.
teleport-cooldown: 0



